### ISSUE TITLE
Unable to read repository at http://marketplace.eclipse.org/content/osx-eclipse-launcher

### ISSUE THREAD

**Issue by rbondi** [turesheim/eclipse-utilities#5268]
Hi, has the link changed? I tried both the "install" dragging, and using the link provided on github. I always get:

Unable to read repository at http://marketplace.eclipse.org/content/osx-eclipse-launcher.
http://marketplace.eclipse.org/content/osx-eclipse-launcher is not a valid repository location.

My specs: OSX 10.10.2

eclipse.buildId=4.4.2.M20150204-1700
java.version=1.7.0_75
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.7
java.vm.vendor=Oracle Corporation
java.vm.version=24.75-b04

**Comment by turesheim** [comment]
That's the link to the marketplace page. Did you drag and drop the "install" button or did you copy the link. In the latter case you will end up wi the wrong URL. Try https://resheim.net/p2/eclipse-utilities/ instead.

**Comment by turesheim** [comment]
I'm guessing the problem was resolved. Closing.
